export enum TokenType {
  VAR = 'VAR',
  CONST = 'CONST',
  FUNCTION = 'FUNCTION',

  IDENTIFIER = 'IDENTIFIER',
  INT = 'INT',
  FLOAT = 'FLOAT',
  STRING = 'STRING',
  BOOLEAN = 'BOOLEAN',
  VOID = 'VOID', 
  
  STRING_ARR = 'STRING_ARR',
  INT_ARR = 'INT_ARR',
  FLOAT_ARR = 'FLOAT_ARR',
  BOOLEAN_ARR = 'BOOLEAN_ARR',

  EQUALS = 'EQUALS',
  COLON = 'COLON',
  SEMICOLON = 'SEMICOLON',
  LPAREN = 'LPAREN',
  RPAREN = 'RPAREN',
  LCURLY = 'LCURLY',
  RCURLY = 'RCURLY',
  LBRACE = 'LBRACE',
  RBRACE = 'RBRACE',
  COMMA = 'COMMA',
  DOT = 'DOT',
  PLUS = 'PLUS',
  MINUS = 'MINUS',
  ASTERISK = 'ASTERISK',
  SLASH = 'SLASH',
  PERCENT = 'PERCENT',
  LT = 'LT',
  GT = 'GT',
  BANG = 'BANG',
  EQUALS_EQUALS = 'EQUALS_EQUALS',
  NOT_EQUALS = 'NOT_EQUALS',
  LT_EQUALS = 'LT_EQUALS',
  GT_EQUALS = 'GT_EQUALS',
  INCREMENT = 'INCREMENT',
  DECREMENT = 'DECREMENT',
  AND = 'AND',
  OR = 'OR',
  QUESTION_MARK = 'QUESTION_MARK',
  TEMPLATE_HEAD = 'TEMPLATE_HEAD',
  TEMPLATE_EXPR_START = 'TEMPLATE_EXPR_START',
  TEMPLATE_TEXT = 'TEMPLATE_TEXT',
  TEMPLATE_EXPR_END = 'TEMPLATE_EXPR_END',
  TEMPLATE_TAIL = 'TEMPLATE_TAIL',

  COMMENT = 'COMMENT',

  IF_STATEMENT = 'IF',
  ELSE_STATEMENT = 'ELSE',
  FOR_STATEMENT = 'FOR',
  DO_STATEMENT = 'DO',
  WHILE_STATEMENT = 'WHILE',
  RETURN_STATEMENT = 'RETURN',

  TYPE_STRING = 'TYPE_STRING',
  TYPE_INT = 'TYPE_INT',
  TYPE_FLOAT = 'TYPE_FLOAT',
  TYPE_BOOLEAN = 'TYPE_BOOLEAN',
  TYPE_VOID = 'TYPE_VOID',

  TYPE_STRING_ARR = 'TYPE_STRING_ARR',
  TYPE_INT_ARR = 'TYPE_INT_ARR',
  TYPE_FLOAT_ARR = 'TYPE_FLOAT_ARR',
  TYPE_BOOLEAN_ARR = 'TYPE_BOOLEAN_ARR',

  ILLEGAL = 'ILLEGAL',
  EOF = 'EOF',

  DISPLAY = 'DISPLAY',
}

export interface Token {
  type: TokenType;
  literal: string;
  line?: number;
  column?: number;
}
